name: Update Quorum Api Github Page

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ">=1.19.0"

      - name: Checkout quorum repo
        uses: actions/checkout@v3

      - name: Swag Init
        run: |
          go install github.com/swaggo/swag/cmd/swag@v1.7.0
          make gen-doc

      - name: Check swagger.json generated
        id: check_files
        uses: andstor/file-existence-action@v1.1.0
        with:
          files: "docs/swagger.json"

      - name: Quit workflow when generating swagger.json failure
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          echo swag init failure
          exit 1

      - name: Upload swagger.json to artifact
        uses: actions/upload-artifact@v3
        with:
          name: quorum-artifact
          path: docs/swagger.json

      - name: Checkout quorum-api repo
        uses: actions/checkout@v3
        with:
          repository: rumsystem/quorum-api
          ssh-key: ${{ secrets.QUORUM_API_ACCESS_KEY }}

      - name: Download swagger.json from artifact
        uses: actions/download-artifact@v3
        with:
          name: quorum-artifact
          path: docs

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "generated from $(git rev-parse --short ${GITHUB_SHA}) of quorum repo"
          git push
